#include <stdio.h>
#include <stdlib.h>

#include "sprite_management.h"

Sprite *mouse;
Sprite *_1computer_button;
Sprite *_2computers_button;
Sprite *exit_button;
Sprite *fireboywatergirl;
Sprite *levels_button;
Sprite *background;
Sprite *levelBackground;
Sprite *NoBorder;
Sprite *Top;
Sprite *Left;
Sprite *Right;
Sprite *Bottom;
Sprite *LeftRight;
Sprite *TopBottom;
Sprite *RightBottom;
Sprite *LeftBottom;
Sprite *TopLeft;
Sprite *TopRight;
Sprite *LeftBottomRight;
Sprite *LeftTopRight;
Sprite *TopRightBottom;
Sprite *TopLeftBottom;
Sprite *Fireboy;
Sprite *Watergirl;
Sprite *FireboyLeft1;
Sprite *FireboyLeft2;
Sprite *FireboyRight1;
Sprite *FireboyRight2;
Sprite *WatergirlLeft1;
Sprite *WatergirlLeft2;
Sprite *WatergirlRight1;
Sprite *WatergirlRight2;
Sprite *FireHoleCenter;
Sprite *FireHoleRight;
Sprite *FireHoleLeft;
Sprite *WaterHoleCenter;
Sprite *WaterHoleRight;
Sprite *WaterHoleLeft;
Sprite *ToxicHoleCenter;
Sprite *ToxicHoleRight;
Sprite *ToxicHoleLeft;
Sprite *ButtonLeft;
Sprite *ButtonRight;
Sprite *ButtonPressedLeft;
Sprite *ButtonPressedRight;
Sprite *leftlever;
Sprite *rightlever;
Sprite *dooropen;
Sprite *doorred;
Sprite *doorblue;
Sprite *AllBorders;
Sprite *PlaceTime;
Sprite *barNumber;
Sprite *pontosNumber;
Sprite *n1;
Sprite *n2;
Sprite *n3;
Sprite *n4;
Sprite *n5;
Sprite *n6;
Sprite *n7;
Sprite *n8;
Sprite *n9;
Sprite *n0;
Sprite* num_sprites[10];
Sprite *youLost;
Sprite *youWon;
Sprite *retry;
Sprite *retryLevel;
Sprite *nextLevel;
Sprite *waitingConnection;

extern uint8_t *framebuffer;

void load_sprites() {
    mouse = create_sprite((xpm_map_t) mouse_xpm);
    _1computer_button = create_sprite((xpm_map_t) _1computer_xpm);
    _2computers_button = create_sprite((xpm_map_t) _2computers_xpm);
    exit_button = create_sprite((xpm_map_t)exit_xpm);
    fireboywatergirl=create_sprite((xpm_map_t)fireboywatergirl_xpm);
    levels_button=create_sprite((xpm_map_t)levels_xpm);
    background=create_sprite((xpm_map_t)background_xpm);
    levelBackground=create_sprite((xpm_map_t)LevelBackground_xpm);
    NoBorder=create_sprite((xpm_map_t)NoBorder_xpm);
    Top=create_sprite((xpm_map_t)Top_xpm);
    Left=create_sprite((xpm_map_t)Left_xpm);
    Right=create_sprite((xpm_map_t)Right_xpm);
    Bottom=create_sprite((xpm_map_t)Bottom_xpm);
    LeftRight=create_sprite((xpm_map_t)RightLeft_xpm);
    TopBottom=create_sprite((xpm_map_t)TopBottom_xpm);
    RightBottom=create_sprite((xpm_map_t)BottomRight_xpm);
    LeftBottom=create_sprite((xpm_map_t)BottomLeft_xpm);
    TopLeft=create_sprite((xpm_map_t)TopLeft_xpm);
    TopRight=create_sprite((xpm_map_t)TopRight_xpm);
    LeftBottomRight=create_sprite((xpm_map_t)LeftRightBottom_xpm);
    LeftTopRight=create_sprite((xpm_map_t)LeftTopRight_xpm);
    TopRightBottom=create_sprite((xpm_map_t)TopRightBottom_xpm);
    TopLeftBottom=create_sprite((xpm_map_t)TopLeftBottom_xpm);
    Fireboy=create_sprite((xpm_map_t) fireboy_xpm);
    Watergirl=create_sprite((xpm_map_t) watergirl_xpm);
    FireboyLeft1=create_sprite((xpm_map_t) FireboyLeft1_xpm);
    FireboyLeft2=create_sprite((xpm_map_t) FireboyLeft2_xpm);
    FireboyRight1=create_sprite((xpm_map_t) FireboyRight1_xpm);
    FireboyRight2=create_sprite((xpm_map_t) FireboyRight2_xpm);
    FireHoleCenter=create_sprite((xpm_map_t) centerblockfire_xpm);
    FireHoleRight=create_sprite((xpm_map_t) rightblockfire_xpm);
    FireHoleLeft=create_sprite((xpm_map_t) leftblockfire_xpm);
    WaterHoleCenter=create_sprite((xpm_map_t) centerblockwater_xpm);
    WaterHoleRight=create_sprite((xpm_map_t) rightblockwater_xpm);
    WaterHoleLeft=create_sprite((xpm_map_t) leftblockwater_xpm);
    ToxicHoleCenter=create_sprite((xpm_map_t) centerblocktoxic_xpm);
    ToxicHoleRight=create_sprite((xpm_map_t) rightblocktoxic_xpm);
    ToxicHoleLeft=create_sprite((xpm_map_t) leftblocktoxic_xpm);
    ButtonRight=create_sprite((xpm_map_t) buttonright_xpm);
    ButtonLeft=create_sprite((xpm_map_t) buttonleft_xpm);
    ButtonPressedRight=create_sprite((xpm_map_t) buttonrightpressed_xpm);
    ButtonPressedLeft=create_sprite((xpm_map_t) buttonleftpressed_xpm);
    leftlever=create_sprite((xpm_map_t) redleverleft_xpm);
    rightlever=create_sprite((xpm_map_t) greenleverright_xpm);
    WatergirlLeft1=create_sprite((xpm_map_t) watergirlLeft1_xpm);
    WatergirlLeft2=create_sprite((xpm_map_t) watergirlLeft2_xpm);
    WatergirlRight1=create_sprite((xpm_map_t) watergirlRight1_xpm);
    WatergirlRight2=create_sprite((xpm_map_t) watergirlRight2_xpm);
    dooropen=create_sprite((xpm_map_t) opendoor_xpm);
    doorred=create_sprite((xpm_map_t) doorred_xpm);
    doorblue=create_sprite((xpm_map_t) doorblue_xpm);
    AllBorders = create_sprite((xpm_map_t) AllBorders_xpm);
    PlaceTime = create_sprite((xpm_map_t) PlaceTime_xpm);
    barNumber = create_sprite((xpm_map_t) barNumber_xpm);
    pontosNumber = create_sprite((xpm_map_t) pontosNumber_xpm);
    n1 = create_sprite((xpm_map_t) n1_xpm);
    n2 = create_sprite((xpm_map_t) n2_xpm);
    n3 = create_sprite((xpm_map_t) n3_xpm);
    n4 = create_sprite((xpm_map_t) n4_xpm);
    n5 = create_sprite((xpm_map_t) n5_xpm);
    n6 = create_sprite((xpm_map_t) n6_xpm);
    n7 = create_sprite((xpm_map_t) n7_xpm);
    n8 = create_sprite((xpm_map_t) n8_xpm);
    n9 = create_sprite((xpm_map_t) n9_xpm);
    n0 = create_sprite((xpm_map_t) n0_xpm);
    num_sprites[0]=n0;
    num_sprites[1]=n1;
    num_sprites[2]=n2;
    num_sprites[3]=n3;
    num_sprites[4]=n4;
    num_sprites[5]=n5;
    num_sprites[6]=n6;
    num_sprites[7]=n7;
    num_sprites[8]=n8;
    num_sprites[9]=n9;
    youLost = create_sprite((xpm_map_t) youLost_xpm);
    youWon = create_sprite((xpm_map_t) youWon_xpm); 
    retry = create_sprite((xpm_map_t) retry_xpm);
    retryLevel = create_sprite((xpm_map_t) retryLevel_xpm);
    nextLevel = create_sprite((xpm_map_t) next_level_xpm);
    waitingConnection = create_sprite((xpm_map_t) waiting_xpm);
}

int drawSprite(Sprite *sprite, int xPos, int yPos) { 
    uint32_t current_color;
    for (int i = 0 ; i < sprite->height; i++) {
      for (int j = 0 ; j < sprite->width; j++) {
          current_color = sprite->map[j + i*sprite->width];
          if (current_color == TRANSPARENT_COLOR) continue;
          if (draw_pixel(xPos + j, yPos + i, current_color, framebuffer)) return 1;
      }
    }
    return 0; 
}

void destroy_sprites() {
    destroy_sprite(mouse);
    destroy_sprite(_1computer_button);
    destroy_sprite(_2computers_button);
    destroy_sprite(exit_button);
    destroy_sprite(fireboywatergirl);
    destroy_sprite(levels_button);
    destroy_sprite(background);
    destroy_sprite(levelBackground);
    destroy_sprite(NoBorder);
    destroy_sprite(Top);
    destroy_sprite(Left);
    destroy_sprite(Right);
    destroy_sprite(Bottom);
    destroy_sprite(LeftRight);
    destroy_sprite(TopBottom);
    destroy_sprite(RightBottom);
    destroy_sprite(LeftBottom);
    destroy_sprite(TopLeft);
    destroy_sprite(TopRight);
    destroy_sprite(LeftBottomRight);
    destroy_sprite(LeftTopRight);
    destroy_sprite(TopRightBottom);
    destroy_sprite(TopLeftBottom);
    destroy_sprite(Fireboy);
    destroy_sprite(Watergirl);
    destroy_sprite(FireboyLeft1);
    destroy_sprite(FireboyLeft2);
    destroy_sprite(FireboyRight1);
    destroy_sprite(FireboyRight2);
    destroy_sprite(FireHoleCenter);
    destroy_sprite(FireHoleRight);
    destroy_sprite(FireHoleLeft);
    destroy_sprite(WaterHoleCenter);
    destroy_sprite(WaterHoleLeft);
    destroy_sprite(WaterHoleRight);
    destroy_sprite(ToxicHoleCenter);
    destroy_sprite(ToxicHoleRight);
    destroy_sprite(ToxicHoleLeft);
    destroy_sprite(ButtonRight);
    destroy_sprite(ButtonLeft);
    destroy_sprite(ButtonPressedRight);
    destroy_sprite(ButtonPressedLeft);
    destroy_sprite(leftlever);
    destroy_sprite(rightlever);
    destroy_sprite(WatergirlLeft1);
    destroy_sprite(WatergirlLeft2);
    destroy_sprite(WatergirlRight1);
    destroy_sprite(WatergirlRight2);
    destroy_sprite(dooropen);
    destroy_sprite(doorred);
    destroy_sprite(doorblue);
    destroy_sprite(AllBorders);
    destroy_sprite(PlaceTime);
    destroy_sprite(barNumber);
    destroy_sprite(pontosNumber);
    destroy_sprite(n1);
    destroy_sprite(n2);
    destroy_sprite(n3);
    destroy_sprite(n4);
    destroy_sprite(n5);
    destroy_sprite(n6);
    destroy_sprite(n7);
    destroy_sprite(n8);
    destroy_sprite(n9);
    destroy_sprite(n0);
    destroy_sprite(youLost);
    destroy_sprite(youWon);
    destroy_sprite(retry);
    destroy_sprite(retryLevel);
    destroy_sprite(nextLevel);
    destroy_sprite(waitingConnection);
}
